name: Terraform Validate Feature Branch Pipeline
run-name: User ${{ github.actor }} is validating terraform on branch ${{ github.ref }}
on:
  push:
    branches:    
      - 'develop'
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: sa-east-1
    steps:
      - name: Install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg &&
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list &&
          sudo apt update && sudo apt install terraform
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Terraform init
        run: |
          cd ${{ github.workspace }} && terraform init
      - name: Terraform validate
        run: cd ${{ github.workspace }} && terraform validate
      - name: Terraform plan
        run: cd ${{ github.workspace }} && terraform plan
      - name: Pull-request branch to main
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into master" 
          pr_body: |                                        
            :crown: *An automated PR*

            _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_